# panelConfig.yaml

# Como tus IDs ya vienen sin prefijo "cell-", lo desactivamos
cellIdPreamble: ""

cells:
  "1rbM0-cvAGEcR-0-JKkf-1":   # nodo1
    query: A
    expression: ${__value.raw}
    thresholds:
      - op: "="
        value: 0
        color: "red"
      - op: ">"
        value: 0
        color: "green"

  "1rbM0-cvAGEcR-0-JKkf-2":   # nodo2
    query: B
    expression: ${__value.raw}
    thresholds:
      - op: "="
        value: 0
        color: "red"
      - op: ">"
        value: 0
        color: "green"

  "1rbM0-cvAGEcR-0-JKkf-3":   # nodo3
    query: C
    expression: ${__value.raw}
    thresholds:
      - op: "="
        value: 0
        color: "red"
      - op: ">"
        value: 0
        color: "green"

  "1rbM0-cvAGEcR-0-JKkf-4":   # nodo4
    query: D
    expression: ${__value.raw}
    thresholds:
      - op: "="
        value: 0
        color: "red"
      - op: ">"
        value: 0
        color: "green"
