cellIdPreamble: ""    # ya incluimos el id completo en el SVG: node-1, node-2…
cells:
  node-1:
    dataRef: "A"
    label:
      units: "none"
      decimalPoints: 0
    fillColor:
      gradientMode: "hue"
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green", level: 1 }
  node-2:
    dataRef: "B"
    label:
      units: "none"
      decimalPoints: 0
    fillColor:
      gradientMode: "hue"
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green", level: 1 }
  node-3:
    dataRef: "C"
    label:
      units: "none"
      decimalPoints: 0
    fillColor:
      gradientMode: "hue"
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green", level: 1 }
  node-4:
    dataRef: "D"
    label:
      units: "none"
      decimalPoints: 0
    fillColor:
      gradientMode: "hue"
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green", level: 1 }
