cellIdPreamble: "cell-"        # ← ya coincide con los id="cell-node-X" del SVG

cells:
  node-1:
    dataRef: "a"
    fillColor:
      gradientMode: "hue"      # usa solo los colores listados; no interpola
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green", level: 1 }

  node-2:
    dataRef: "b"
    fillColor:
      gradientMode: "hue"
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green", level: 1 }

  node-3:
    dataRef: "c"
    fillColor:
      gradientMode: "hue"
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green", level: 1 }

  node-4:
    dataRef: "d"
    fillColor:
      gradientMode: "hue"
      thresholds:
        - { color: "red",   level: 0 }
        - { color: "green", level: 1 }
