# panelConfig.yaml
cellIdPreamble: ""  # no prefix
cells:
  "node-1":
    query: A
    expression: ${__value.raw}
    thresholds:
      - op: "="
        value: 0
        color: "red"
      - op: ">"
        value: 0
        color: "green"
  "node-2":
    query: B
    expression: ${__value.raw}
    thresholds:
      - op: "="
        value: 0
        color: "red"
      - op: ">"
        value: 0
        color: "green"
  "node-3":
    query: C
    expression: ${__value.raw}
    thresholds:
      - op: "="
        value: 0
        color: "red"
      - op: ">"
        value: 0
        color: "green"
  "node-4":
    query: D
    expression: ${__value.raw}
    thresholds:
      - op: "="
        value: 0
        color: "red"
      - op: ">"
        value: 0
        color: "green"
