cellIdPreamble: "cell-"

cells:
  node-1:
    dataRef: "A"          # alias de tu query
    reducer: last         # ← ESTA línea hace el trabajo
    fillColor:
      gradientMode: hue
      thresholds:
        - { color: red,   level: 0 }
        - { color: green, level: 1 }

  node-2:
    dataRef: "B"
    reducer: last
    fillColor:
      gradientMode: hue
      thresholds:
        - { color: red,   level: 0 }
        - { color: green, level: 1 }

  node-3:
    dataRef: "C"
    reducer: last
    fillColor:
      gradientMode: hue
      thresholds:
        - { color: red,   level: 0 }
        - { color: green, level: 1 }

  node-4:
    dataRef: "D"
    reducer: last
    fillColor:
      gradientMode: hue
      thresholds:
        - { color: red,   level: 0 }
        - { color: green, level: 1 }
